import { reactive } from "vue";

const all = reactive ({
    getAll: [],
    spliceAll: [],
    splice: [],
    modelFalse: false,
    theModelFalse: false,
    buttonFalse: true,
    theButtonFalse: true,
    listOneFalse: true,
    listTwoFalse: true,
    listThreeFalse: true,
    listFourFalse: true,
    listFiveFalse: true,
    listSixFalse: true,
    listSevenFalse: true,
    listEightFalse: true,
    getById: {},
    email: '',
    password: '',
    allShow: true,
    userShow: false,
    price: null,
    curs: '',
    dogovor: false,
    room: null,
    roomTwo: null,
    roomThree: null,
    checkOne: false,
    checkTwo: false,
    checkThree: false,
    checkFour: false,
    checkFive: false,
    checkSix: false,
    checkSeven: false,
    checkEight: false,
    home: null,
    height: '',
    sqaure: null,
    boxOne: false,
    boxTwo: false,
    boxThree: false,
    boxFour: false,
    boxFive: false,
    boxSeven: false,
    boxSix: false,
    boxEight: false,
    type: '',
    Electricity: '',
    input: '',
    region: '',
    city: '',
    tel: null,
    adres: '',
    face: ''
})

export{
    all
}